#include "ppbng_core/frame_context_writer.hpp"
#include <gtest/gtest.h>
#include <chrono>
#include <fstream>
#include <sstream>
namespace {struct Temp{std::filesystem::path p=std::filesystem::temp_directory_path()/("ppbctx_"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));Temp(){std::filesystem::create_directories(p/"segments");}~Temp(){std::error_code e;std::filesystem::remove_all(p,e);}};}
TEST(FrameContextWriter, ExclusiveAppendFlushFinalize){Temp t;auto[a,w]=ppbng_core::FrameContextWriter::create({t.p,"ctx"});ASSERT_TRUE(a.ok);ppbng_core::FrameContextResult c;c.gnss_detail="missing bracket";ASSERT_TRUE(w->append({"s","rgb",1,2,3,4},c).ok);EXPECT_TRUE(w->close().ok);auto[b,w2]=ppbng_core::FrameContextWriter::create({t.p,"ctx"});EXPECT_FALSE(b.ok);}
TEST(FrameContextWriter, ReportsWriteFailure){Temp t;auto[a,w]=ppbng_core::FrameContextWriter::create({t.p,"ctx",0});ASSERT_TRUE(a.ok);EXPECT_FALSE(w->append({"s","thermal",1,2,3,4},{}).ok);}
TEST(FrameContextWriter, PersistsGnssPitchRsmYawAndEndpointStatus){Temp t;auto[a,w]=ppbng_core::FrameContextWriter::create({t.p,"ctx"});ASSERT_TRUE(a.ok);ppbng_core::FrameContextResult c;c.heading_deg=12.0;c.pitch_deg=3.5;ppbng_core::AssociatedRsmAttitude r;r.before_sample_id=10;r.after_sample_id=11;r.roll_deg=1.0;r.pitch_deg=2.0;r.yaw_deg=359.0;r.before_raw_status=2;r.after_raw_status=3;c.rsm=r;c.rsm_status=ppbng_core::ContextAvailability::degraded;ASSERT_TRUE(w->append({"s","rgb",1,2,3,4},c).ok);ASSERT_TRUE(w->close().ok);std::ifstream input(t.p/"segments"/"ctx.ndjson");std::ostringstream text;text<<input.rdbuf();EXPECT_NE(text.str().find("\"gnss_pitch_deg\":3.5"),std::string::npos);EXPECT_NE(text.str().find("\"yaw_valid\":true,\"yaw_deg\":359"),std::string::npos);EXPECT_NE(text.str().find("\"rsm_before_raw_status\":2"),std::string::npos);EXPECT_NE(text.str().find("\"rsm_after_raw_status\":3"),std::string::npos);EXPECT_NE(text.str().find("\"rsm_measurement_type\":\"gimbal_angles\""),std::string::npos);EXPECT_NE(text.str().find("\"rsm_reference_frame\":\"rsm400_base_plate\""),std::string::npos);EXPECT_NE(text.str().find("\"rsm_earth_referenced\":false"),std::string::npos);}
TEST(FrameContextWriter, PersistsCompleteSampleStampEvidence){Temp t;auto[a,w]=ppbng_core::FrameContextWriter::create({t.p,"ctx"});ASSERT_TRUE(a.ok);ppbng_core::ContextFrameIdentity f;f.session_id="s";f.device_id="thermal";f.segment_id=7;f.sample_sequence=8;f.utc_ns=9;f.host_ns=10;f.trigger_channel="thermal";f.trigger_sequence=11;f.pps_sequence=12;f.controller_tick=13;f.controller_ticks_per_second=1000000;f.time_uncertainty_ns=14;f.time_status=1;f.time_detail="holdover evidence";f.camera_frame_id_valid=true;f.camera_frame_id=15;f.camera_timestamp_valid=true;f.camera_timestamp=16;ASSERT_TRUE(w->append(f,{}).ok);ASSERT_TRUE(w->close().ok);std::ifstream input(t.p/"segments"/"ctx.ndjson");std::ostringstream text;text<<input.rdbuf();const auto value=text.str();EXPECT_NE(value.find("\"trigger_channel\":\"thermal\""),std::string::npos);EXPECT_NE(value.find("\"trigger_sequence\":11"),std::string::npos);EXPECT_NE(value.find("\"pps_sequence\":12"),std::string::npos);EXPECT_NE(value.find("\"time_uncertainty_ns\":14"),std::string::npos);EXPECT_NE(value.find("\"time_detail\":\"holdover evidence\""),std::string::npos);EXPECT_NE(value.find("\"camera_frame_id_valid\":true"),std::string::npos);EXPECT_NE(value.find("\"camera_timestamp\":16"),std::string::npos);}
TEST(FrameContextWriter, PersistsThermalNucSnapshotForEverySensorFrame){Temp t;auto[a,w]=ppbng_core::FrameContextWriter::create({t.p,"ctx"});ASSERT_TRUE(a.ok);ppbng_core::ContextFrameIdentity f;f.session_id="s";f.device_id="fx10e";f.thermal_nuc_state_valid=true;f.thermal_nuc_active=true;f.thermal_nuc_state_sequence=4;f.thermal_nuc_observed_host_monotonic_ns=123;f.thermal_correction_auto_in_progress=true;f.thermal_correction_status="CollectingData";f.thermal_flag_state="InFOV";f.thermal_nuc_detail="robot stop requested";ASSERT_TRUE(w->append(f,{}).ok);ASSERT_TRUE(w->close().ok);std::ifstream input(t.p/"segments"/"ctx.ndjson");std::ostringstream text;text<<input.rdbuf();const auto value=text.str();EXPECT_NE(value.find("\"device_id\":\"fx10e\""),std::string::npos);EXPECT_NE(value.find("\"thermal_nuc_active\":true"),std::string::npos);EXPECT_NE(value.find("\"thermal_correction_status\":\"CollectingData\""),std::string::npos);EXPECT_NE(value.find("\"thermal_flag_state\":\"InFOV\""),std::string::npos);}
