#include "ppbng_core/frame_context_association.hpp"
#include "ppbng_core/frame_context_writer.hpp"
#include "ppbng_core/gga_utc_resolver.hpp"
#include <ppbng_interfaces/msg/fault_event.hpp>
#include <ppbng_interfaces/msg/frame_context.hpp>
#include <ppbng_interfaces/msg/frame_metadata.hpp>
#include <ppbng_interfaces/msg/gnss_observation.hpp>
#include <ppbng_interfaces/msg/rsm_telemetry.hpp>
#include <ppbng_interfaces/msg/sample_stamp.hpp>
#include <ppbng_interfaces/srv/prepare_device.hpp>
#include <rclcpp/rclcpp.hpp>
#include <std_srvs/srv/trigger.hpp>
#include <algorithm>
#include <chrono>
#include <deque>
#include <filesystem>
#include <limits>
#include <mutex>
#include <unordered_map>
namespace ppbng_core {
class FrameContextNode final:public rclcpp::Node{public:
 FrameContextNode():Node("frame_context"),association_(declare_parameter<int64_t>("gnss_max_bracket_span_ns",2000000000LL),declare_parameter<int64_t>("gnss_max_endpoint_age_ns",1500000000LL),declare_parameter<int64_t>("rsm_max_endpoint_age_ns",1000000000LL)),resolver_(declare_parameter<int64_t>("gga_anchor_max_age_ns",3000000000LL),declare_parameter<int64_t>("gga_clock_residual_ns",200000000LL)){
  allowed_root_=declare_parameter<std::string>("allowed_output_root","");auto wait=declare_parameter<int64_t>("frame_context_max_wait_ns",2000000000LL);if(wait<=0)throw std::invalid_argument("frame context max wait must be positive");max_wait_ns_=static_cast<std::uint64_t>(wait);publisher_=create_publisher<ppbng_interfaces::msg::FrameContext>("~/frame_context",100);faults_=create_publisher<ppbng_interfaces::msg::FaultEvent>("~/fault_event",10);auto fq=declare_parameter<std::string>("rgb_frame_topic","/rgb/frame_metadata");auto tq=declare_parameter<std::string>("thermal_frame_topic","/thermal/frame_metadata");
  auto hq=declare_parameter<std::string>("hsi_sample_stamp_topic","/acquisition/sample_stamp");frames_rgb_=create_subscription<ppbng_interfaces::msg::FrameMetadata>(fq,100,[this](const ppbng_interfaces::msg::FrameMetadata&m){frame(m.stamp);});frames_thermal_=create_subscription<ppbng_interfaces::msg::FrameMetadata>(tq,100,[this](const ppbng_interfaces::msg::FrameMetadata&m){frame(m.stamp);});frames_hsi_=create_subscription<ppbng_interfaces::msg::SampleStamp>(hq,200,[this](const ppbng_interfaces::msg::SampleStamp&m){frame(m);});gnss_=create_subscription<ppbng_interfaces::msg::GnssObservation>("/gnss/observation",100,[this](const ppbng_interfaces::msg::GnssObservation&m){gnss(m);});rsm_=create_subscription<ppbng_interfaces::msg::RsmTelemetry>("/rsm400/telemetry",100,[this](const ppbng_interfaces::msg::RsmTelemetry&m){rsm(m);});
  using P=ppbng_interfaces::srv::PrepareDevice;prepare_=create_service<P>("~/prepare",[this](const std::shared_ptr<P::Request>q,std::shared_ptr<P::Response>r){prepare(q,r);});using T=std_srvs::srv::Trigger;arm_=create_service<T>("~/arm",[this](const std::shared_ptr<T::Request>,std::shared_ptr<T::Response>r){std::lock_guard<std::mutex>l(m_);r->success=prepared_&&!running_;r->message=r->success?"context recorder armed without creating files":"prepare required while inert";armed_=r->success;});start_=create_service<T>("~/start",[this](const std::shared_ptr<T::Request>,std::shared_ptr<T::Response>r){start(r);});stop_=create_service<T>("~/stop",[this](const std::shared_ptr<T::Request>,std::shared_ptr<T::Response>r){stop(r);});
 }
private:struct Prep{std::string sid,dir,msg;bool ok;};struct Pending{ppbng_interfaces::msg::SampleStamp stamp;std::uint64_t receipt;};static std::uint64_t mono(){return std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now().time_since_epoch()).count();}static std::int64_t utc(const builtin_interfaces::msg::Time&t){return static_cast<std::int64_t>(t.sec)*1000000000LL+t.nanosec;}
 void prepare(const std::shared_ptr<ppbng_interfaces::srv::PrepareDevice::Request>&q,std::shared_ptr<ppbng_interfaces::srv::PrepareDevice::Response>r){std::lock_guard<std::mutex>l(m_);auto old=history_.find(q->request_id);if(old!=history_.end()){bool same=old->second.sid==q->session_id&&old->second.dir==q->session_directory;r->accepted=same&&old->second.ok;r->duplicate_request=same;r->message=same?old->second.msg:"request_id payload mismatch";return;}auto done=[&](bool ok,std::string d){history_[q->request_id]={q->session_id,q->session_directory,d,ok};r->accepted=ok;r->message=d;};if(q->request_id.empty()||running_){done(false,"nonempty request_id and inert state required");return;}std::error_code e;auto root=std::filesystem::weakly_canonical(allowed_root_,e);auto dir=std::filesystem::weakly_canonical(q->session_directory,e);auto rel=dir.lexically_relative(root);if(e||q->session_id.empty()||root==dir||rel.empty()||rel.is_absolute()||*rel.begin()==".."||!std::filesystem::is_directory(dir/"segments",e)){done(false,"session must be existing child of allowed root with segments");return;}session_=q->session_id;directory_=dir;prepared_=true;armed_=false;done(true,"context session bound");}
 void start(std::shared_ptr<std_srvs::srv::Trigger::Response>r){std::lock_guard<std::mutex>l(m_);if(!prepared_||!armed_||running_){r->message="prepared armed inert context recorder required";return;}auto[x,w]=FrameContextWriter::create({directory_,"frame_context"});if(!x.ok){storage_fault(x.detail);r->message=x.detail;return;}writer_=std::move(w);association_.reset();resolver_.reset();pending_.clear();unresolved_gga_.clear();running_=true;r->success=true;r->message="context recorder started";}
 void stop(std::shared_ptr<std_srvs::srv::Trigger::Response>r){std::lock_guard<std::mutex>l(m_);if(running_){drain(true);auto c=writer_->close();if(!c.ok)storage_fault(c.detail);writer_.reset();}running_=false;armed_=false;r->success=!faulted_;r->message=faulted_?fault_detail_:"context recorder finalized";}
 void storage_fault(const std::string&d){faulted_=true;fault_detail_=d;ppbng_interfaces::msg::FaultEvent e;e.event_id="context-storage-"+std::to_string(++events_);e.session_id=session_;e.source_id="context";e.fault_code="FRAME_CONTEXT_STORAGE_FAULT";e.severity=e.SEVERITY_FATAL;e.first_host_monotonic_ns=mono();e.last_host_monotonic_ns=e.first_host_monotonic_ns;e.occurrence_count=1;e.latched=true;e.causes_global_stop=true;e.detail=d;faults_->publish(e);running_=false;}
 void gnss(const ppbng_interfaces::msg::GnssObservation&m){std::lock_guard<std::mutex>l(m_);if(!running_||m.session_id!=session_)return;if(m.receiver_utc_valid){auto t=utc(m.receiver_utc);if(resolver_.observe_anchor({m.sample_sequence,m.connection_epoch,m.host_receive_monotonic_ns,t})&&m.heading_valid)association_.add_gnss_heading({m.sample_sequence,t,m.host_receive_monotonic_ns,m.heading_deg,m.pitch_deg,true});for(auto i=unresolved_gga_.begin();i!=unresolved_gga_.end();){auto x=resolver_.resolve(i->gga_utc_hhmmss,i->host_receive_monotonic_ns,i->connection_epoch);if(x){add_position(*i,*x);i=unresolved_gga_.erase(i);}else ++i;}}if(m.gga_valid){auto x=resolver_.resolve(m.gga_utc_hhmmss,m.host_receive_monotonic_ns,m.connection_epoch);if(x)add_position(m,*x);else{unresolved_gga_.push_back(m);if(unresolved_gga_.size()>64)unresolved_gga_.pop_front();}}drain(false);}
 void add_position(const ppbng_interfaces::msg::GnssObservation&m,const ResolvedGgaUtc&t){GnssObservation g;g.sequence=m.sample_sequence;g.utc_nanoseconds=t.utc_nanoseconds;g.host_monotonic_nanoseconds=m.host_receive_monotonic_ns;g.latitude_degrees=m.latitude_deg;g.longitude_degrees=m.longitude_deg;g.altitude_meters=m.altitude_m;g.fix_quality=static_cast<std::uint8_t>(std::clamp(m.fix_quality,0,255));g.position_valid=m.gga_valid;g.utc_anchor_sequence=t.anchor_sequence;g.utc_anchor_host_delta_nanoseconds=t.host_delta_ns;g.utc_anchor_clock_residual_nanoseconds=t.clock_residual_ns;association_.add_gnss_position(g);}
 void rsm(const ppbng_interfaces::msg::RsmTelemetry&m){std::lock_guard<std::mutex>l(m_);if(!running_||m.session_id!=session_||m.host_receive_monotonic_ns>(std::numeric_limits<std::int64_t>::max)())return;association_.add_rsm({m.sample_sequence,static_cast<std::int64_t>(m.host_receive_monotonic_ns),m.roll_deg,m.pitch_deg,m.yaw_deg,m.general_status_valid,m.roll_valid,m.pitch_valid,m.yaw_valid,static_cast<std::uint32_t>(m.error_level)});drain(false);}
 void frame(const ppbng_interfaces::msg::SampleStamp&m){std::lock_guard<std::mutex>l(m_);if(!running_||m.session_id!=session_)return;pending_.push_back({m,mono()});drain(false);}
 void drain(bool final){auto now=mono();for(auto i=pending_.begin();i!=pending_.end();){auto&f=i->stamp;auto target=utc(f.time_quality.utc_time);FrameContextQuery q{f.time_quality.status==f.time_quality.UNSYNCED?0:target,f.host_receive_monotonic_ns};auto c=association_.associate(q);if(f.time_quality.status==f.time_quality.HOLDOVER&&c.gnss_status==ContextAvailability::available){c.gnss_status=ContextAvailability::degraded;c.gnss_detail+="; frame UTC is HOLDOVER";}bool ready=c.gnss_status!=ContextAvailability::unavailable&&c.rsm_status!=ContextAvailability::unavailable;bool expired=final||now-i->receipt>=max_wait_ns_;if(!ready&&!expired)break;ContextFrameIdentity id{session_,f.device_id,f.segment_id,f.sample_sequence,q.utc_nanoseconds,q.host_monotonic_ns,f.trigger_channel,f.trigger_sequence,f.pps_sequence,f.controller_tick,f.controller_ticks_per_second,f.time_quality.uncertainty_ns,f.time_quality.status,f.time_quality.detail,f.camera_frame_id_valid,f.camera_frame_id,f.camera_timestamp_valid,f.camera_timestamp};auto wr=writer_->append(id,c);if(!wr.ok){storage_fault(wr.detail);return;}publish(f,c);i=pending_.erase(i);}}
 void publish(ppbng_interfaces::msg::SampleStamp f,const FrameContextResult&c){if(f.time_quality.status==f.time_quality.UNSYNCED){f.time_quality.utc_time.sec=0;f.time_quality.utc_time.nanosec=0;}ppbng_interfaces::msg::FrameContext m;m.frame_stamp=f;m.gnss_status=static_cast<uint8_t>(c.gnss_status);m.gnss_detail=c.gnss_detail;if(c.gnss){m.gnss_before_sequence=c.gnss->before_sequence;m.gnss_after_sequence=c.gnss->after_sequence;m.gnss_before_age_ns=c.gnss->before_age_nanoseconds;m.gnss_after_age_ns=c.gnss->after_age_nanoseconds;m.latitude_deg=c.gnss->latitude_degrees;m.longitude_deg=c.gnss->longitude_degrees;m.altitude_m=c.gnss->altitude_meters;m.before_fix_quality=c.gnss->before_fix_quality;m.after_fix_quality=c.gnss->after_fix_quality;m.gnss_before_utc_anchor_sequence=c.gnss->before_utc_anchor_sequence;m.gnss_after_utc_anchor_sequence=c.gnss->after_utc_anchor_sequence;m.gnss_before_anchor_host_delta_ns=c.gnss->before_utc_anchor_host_delta_nanoseconds;m.gnss_after_anchor_host_delta_ns=c.gnss->after_utc_anchor_host_delta_nanoseconds;m.gnss_before_anchor_clock_residual_ns=c.gnss->before_utc_anchor_clock_residual_nanoseconds;m.gnss_after_anchor_clock_residual_ns=c.gnss->after_utc_anchor_clock_residual_nanoseconds;}m.heading_valid=c.heading_deg.has_value();if(c.heading_deg){m.heading_deg=*c.heading_deg;m.gnss_pitch_deg=*c.pitch_deg;}m.rsm_status=static_cast<uint8_t>(c.rsm_status);m.rsm_detail=c.rsm_detail;if(c.rsm){m.rsm_before_sequence=c.rsm->before_sample_id;m.rsm_after_sequence=c.rsm->after_sample_id;m.rsm_before_age_ns=c.rsm->before_age_nanoseconds;m.rsm_after_age_ns=c.rsm->after_age_nanoseconds;m.roll_deg=c.rsm->roll_deg;m.pitch_deg=c.rsm->pitch_deg;m.yaw_valid=c.rsm->yaw_deg.has_value();if(c.rsm->yaw_deg)m.yaw_deg=*c.rsm->yaw_deg;}publisher_->publish(m);}
 std::mutex m_;FrameContextAssociator association_;GgaUtcResolver resolver_;std::string allowed_root_,session_,fault_detail_;std::filesystem::path directory_;std::uint64_t max_wait_ns_{},events_{};bool prepared_{},armed_{},running_{},faulted_{};std::unordered_map<std::string,Prep>history_;std::deque<Pending>pending_;std::deque<ppbng_interfaces::msg::GnssObservation>unresolved_gga_;std::unique_ptr<FrameContextWriter>writer_;rclcpp::Publisher<ppbng_interfaces::msg::FrameContext>::SharedPtr publisher_;rclcpp::Publisher<ppbng_interfaces::msg::FaultEvent>::SharedPtr faults_;rclcpp::Subscription<ppbng_interfaces::msg::FrameMetadata>::SharedPtr frames_rgb_,frames_thermal_;rclcpp::Subscription<ppbng_interfaces::msg::SampleStamp>::SharedPtr frames_hsi_;rclcpp::Subscription<ppbng_interfaces::msg::GnssObservation>::SharedPtr gnss_;rclcpp::Subscription<ppbng_interfaces::msg::RsmTelemetry>::SharedPtr rsm_;rclcpp::Service<ppbng_interfaces::srv::PrepareDevice>::SharedPtr prepare_;rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr arm_,start_,stop_;
};}
int main(int argc,char**argv){rclcpp::init(argc,argv);rclcpp::spin(std::make_shared<ppbng_core::FrameContextNode>());rclcpp::shutdown();}
