#include "ppbng_rgb/mock_rgb_backend.hpp"
namespace ppbng_rgb
{
MockRgbBackend::MockRgbBackend(FakeRgbNodeMap n):nodes_(std::move(n)),release_count_(std::make_shared<std::atomic_uint64_t>(0)){}
Status MockRgbBackend::preflight(std::chrono::milliseconds t,const StopToken&s)const{if(s.stop_requested())return{ErrorCode::cancelled,"stop requested"};if(t.count()<=0)return{ErrorCode::timeout,"positive timeout required"};return{};}
Status MockRgbBackend::discover(std::chrono::milliseconds t,const StopToken&s,std::vector<std::string>&ids){auto x=preflight(t,s);if(!x.ok())return x;if(!nodes_.discoverable)return{ErrorCode::not_found,"mock absent"};ids={"mock-bfs-u3-122s6"};state_=LifecycleState::discovered;return{};}
Status MockRgbBackend::open(const std::string&id,std::chrono::milliseconds t,const StopToken&s){auto x=preflight(t,s);if(!x.ok())return x;if(state_!=LifecycleState::discovered||id!="mock-bfs-u3-122s6")return{ErrorCode::invalid_state,"discover first"};if(!nodes_.control_access)return{ErrorCode::access_denied,"control required"};state_=LifecycleState::open;return{};}
Status MockRgbBackend::configure(const RgbConfiguration&c,std::chrono::milliseconds t,const StopToken&s){auto x=preflight(t,s);if(!x.ok())return x;if(state_!=LifecycleState::open)return{ErrorCode::invalid_state,"open first"};requested_=c;nodes_.values=c;if(nodes_.force_readback_mismatch)nodes_.values.pixel_format="RGB8";RgbReadback r;x=readback(t,s,r);if(!x.ok())return x;if(configuration_hash(c)!=configuration_hash(r))return{ErrorCode::readback_mismatch,"configuration hash mismatch"};x=validate_raw_bayer_contract(r);if(!x.ok())return x;state_=LifecycleState::configured;return{};}
Status MockRgbBackend::readback(std::chrono::milliseconds t,const StopToken&s,RgbReadback&r){auto x=preflight(t,s);if(!x.ok())return x;if(state_!=LifecycleState::open&&state_!=LifecycleState::configured&&state_!=LifecycleState::armed&&state_!=LifecycleState::streaming)return{ErrorCode::invalid_state,"not open"};static_cast<RgbConfiguration&>(r)=nodes_.values;r.control_access=nodes_.control_access;return{};}
Status MockRgbBackend::arm(std::chrono::milliseconds t,const StopToken&s){auto x=preflight(t,s);if(!x.ok())return x;if(state_!=LifecycleState::configured)return{ErrorCode::invalid_state,"configure first"};RgbReadback r;x=readback(t,s,r);if(!x.ok())return x;x=validate_raw_bayer_contract(r);if(!x.ok())return x;state_=LifecycleState::armed;return{};}
FrameResult MockRgbBackend::next_frame(std::chrono::milliseconds t,const StopToken&s){auto x=preflight(t,s);if(!x.ok())return{x,{}};if(state_!=LifecycleState::armed&&state_!=LifecycleState::streaming)return{{ErrorCode::invalid_state,"arm first"},{}};state_=LifecycleState::streaming;++frame_id_;bool complete=nodes_.incomplete_every_n_frames==0||frame_id_%nodes_.incomplete_every_n_frames!=0;auto data=std::make_shared<std::vector<std::byte>>(nodes_.values.payload_bytes);auto count=release_count_;const auto host_ns=static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now().time_since_epoch()).count());FrameInfo info{frame_id_,segment_index_,data->size(),complete,nodes_.values.pixel_format,frame_id_*1'000'000U,host_ns};info.chunk_data_valid=true;info.chunk_frame_id_valid=true;info.chunk_frame_id=frame_id_;info.chunk_timestamp_valid=true;info.chunk_timestamp=frame_id_*1'000'000U;info.exposure_time_valid=true;info.exposure_time_us=1000.0;info.gain_valid=true;info.gain_db=0.0;info.black_level_valid=true;info.black_level=0.0;info.white_balance_red_valid=true;info.white_balance_red=1.5;info.white_balance_blue_valid=true;info.white_balance_blue=1.25;info.exposure_auto=nodes_.values.exposure_auto;info.gain_auto=nodes_.values.gain_auto;info.balance_white_auto=nodes_.values.balance_white_auto;FrameLease f(std::move(info),data,[count](){++(*count);});return{complete?Status{}:Status{ErrorCode::incomplete_frame,"mock incomplete"},std::move(f)};}
Status MockRgbBackend::recover(std::chrono::milliseconds t,const StopToken&s){auto x=preflight(t,s);if(!x.ok())return x;if(state_!=LifecycleState::armed&&state_!=LifecycleState::streaming&&state_!=LifecycleState::faulted)return{ErrorCode::invalid_state,"active state required"};++segment_index_;frame_id_=0;state_=LifecycleState::open;return{};}
Status MockRgbBackend::stop(std::chrono::milliseconds t)noexcept{if(t.count()<=0)return{ErrorCode::timeout,"positive timeout required"};state_=LifecycleState::stopped;return{};}
} // namespace ppbng_rgb
