#include "ppbng_rgb/rgb_adapter.hpp"
#include <algorithm>
#include <limits>
#include <stdexcept>
namespace ppbng_rgb
{
bool StopToken::stop_requested()const noexcept{return flag_&&flag_->load();}
StopSource::StopSource():flag_(std::make_shared<std::atomic_bool>(false)){} void StopSource::request_stop()noexcept{flag_->store(true);}
namespace {void hb(std::uint64_t&h,const std::string&v){for(unsigned char b:v){h^=b;h*=1099511628211ULL;}h^='|';h*=1099511628211ULL;} template<class T>void hv(std::uint64_t&h,T v){hb(h,std::to_string(v));}}
std::uint64_t configuration_hash(const RgbConfiguration&c)noexcept{std::uint64_t h=14695981039346656037ULL;hv(h,c.width);hv(h,c.height);hv(h,c.row_stride_bytes);hv(h,c.payload_bytes);hb(h,c.pixel_format);hb(h,c.acquisition_mode);hb(h,c.trigger_selector);hb(h,c.trigger_source);hb(h,c.trigger_activation);hb(h,c.exposure_auto);hb(h,c.gain_auto);hb(h,c.balance_white_auto);hb(h,c.balance_white_auto_profile);hb(h,c.auto_exposure_control_priority);hv(h,c.auto_exposure_time_upper_limit_us);hv(h,c.auto_exposure_gain_upper_limit_db);hv(h,c.chunk_data_enabled);hv(h,c.hardware_trigger);return h;}
Status validate_raw_bayer_contract(const RgbReadback&r)
{if(!r.control_access)return{ErrorCode::access_denied,"control access required"}; if(r.width==0||r.height==0||r.row_stride_bytes<r.width||r.height>std::numeric_limits<std::size_t>::max()/r.row_stride_bytes||r.payload_bytes!=r.row_stride_bytes*r.height)return{ErrorCode::invalid_configuration,"invalid packed Bayer layout"}; if(r.pixel_format.rfind("Bayer",0)!=0||r.acquisition_mode!="Continuous"||r.trigger_selector!="FrameStart"||r.trigger_source.empty()||r.trigger_source=="Software"||r.trigger_activation.empty()||!r.hardware_trigger)return{ErrorCode::invalid_configuration,"raw Bayer external FrameStart-trigger contract required"};if(!r.chunk_data_enabled)return{ErrorCode::invalid_configuration,"per-frame RGB Chunk Data is required"};if(r.exposure_auto.empty()||r.gain_auto.empty()||r.balance_white_auto.empty()||r.balance_white_auto_profile.empty()||r.auto_exposure_control_priority.empty()||r.auto_exposure_time_upper_limit_us<=0.0||r.auto_exposure_gain_upper_limit_db<0.0)return{ErrorCode::invalid_configuration,"bounded RGB auto-control policy readback is required"}; return{};}
Status select_unique_device_id(const std::string&expected,const std::vector<std::string>&ids,std::string&selected)
{selected.clear();if(expected.empty())return{ErrorCode::invalid_configuration,"an explicit camera serial/device id is required"};const auto matches=static_cast<std::size_t>(std::count(ids.begin(),ids.end(),expected));if(matches==0)return{ErrorCode::not_found,"configured camera id was not discovered"};if(matches!=1)return{ErrorCode::invalid_configuration,"configured camera id is not unique"};selected=expected;return{};}
FrameLease::FrameLease(FrameInfo i,std::shared_ptr<std::vector<std::byte>>s,std::function<void()>r):info_(std::move(i)),storage_(std::move(s)),release_(std::move(r)){} FrameLease::~FrameLease(){release();}
FrameLease::FrameLease(FrameLease&&o)noexcept:info_(std::move(o.info_)),storage_(std::move(o.storage_)),release_(std::move(o.release_)){o.release_={};o.storage_.reset();} FrameLease&FrameLease::operator=(FrameLease&&o)noexcept{if(this!=&o){release();info_=std::move(o.info_);storage_=std::move(o.storage_);release_=std::move(o.release_);o.release_={};o.storage_.reset();}return *this;} void FrameLease::release()noexcept{if(release_){auto cb=std::move(release_);storage_.reset();cb();}else storage_.reset();}
BoundedFrameQueue::BoundedFrameQueue(std::size_t c):capacity_(c){if(c==0)throw std::invalid_argument("capacity must be positive");}
bool BoundedFrameQueue::try_push(FrameLease f){std::lock_guard<std::mutex>l(mutex_);if(queue_.size()>=capacity_){++statistics_.backpressure_events;++statistics_.dropped_newest;return false;}queue_.push_back(std::move(f));++statistics_.pushed;condition_.notify_one();return true;}
FrameResult BoundedFrameQueue::pop(std::chrono::milliseconds t,const StopToken&s){if(t.count()<=0)return{{ErrorCode::timeout,"positive timeout required"},{}};std::unique_lock<std::mutex>l(mutex_);auto d=std::chrono::steady_clock::now()+t;while(queue_.empty()&&!s.stop_requested()){if(condition_.wait_until(l,d)==std::cv_status::timeout)break;}if(s.stop_requested())return{{ErrorCode::cancelled,"stop requested"},{}};if(queue_.empty())return{{ErrorCode::timeout,"queue timeout"},{}};auto f=std::move(queue_.front());queue_.pop_front();++statistics_.popped;return{{},std::move(f)};}
QueueStatistics BoundedFrameQueue::statistics()const{std::lock_guard<std::mutex>l(mutex_);return statistics_;}
} // namespace ppbng_rgb
