#include "ppbng_rgb/runtime_contract.hpp"
#include "ppbng_rgb/spinnaker_rgb_backend.hpp"
#include "ppbng_rgb/start_cleanup_guard.hpp"
#include "ppbng_rgb/sequence_association.hpp"
#include "ppbng_rgb/recovery_supervisor.hpp"
#include <ppbng_interfaces/msg/frame_metadata.hpp>
#include <ppbng_interfaces/msg/device_status.hpp>
#include <ppbng_interfaces/msg/fault_event.hpp>
#include <ppbng_interfaces/msg/trigger_event.hpp>
#include <ppbng_interfaces/srv/prepare_device.hpp>
#include <ppbng_storage/segment_io.hpp>
#include <ppbng_storage/json_escape.hpp>
#include <rclcpp/rclcpp.hpp>
#include <std_srvs/srv/trigger.hpp>
#include <algorithm>
#include <atomic>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <limits>
#include <memory>
#include <mutex>
#include <sstream>
#include <thread>
#include <unordered_map>
#include <chrono>
#include <condition_variable>
namespace ppbng_rgb {
class RgbCameraNode final:public rclcpp::Node {
public:
 RgbCameraNode():Node("ppbng_rgb_camera"),backend_(std::make_unique<SpinnakerRgbBackend>()){
  declare_parameter<bool>("association_evidence_confirmed",false);
  allow_hardware_=declare_parameter<bool>("allow_hardware_access",false);allowed_output_root_=declare_parameter<std::string>("allowed_output_root","");device_id_=declare_parameter<std::string>("device_id","");session_id_=declare_parameter<std::string>("session_id","");session_root_=declare_parameter<std::string>("session_root","");stream_name_=declare_parameter<std::string>("stream_name","rgb");timeout_ms_=declare_parameter<int>("acquisition_timeout_ms",1000);auto mb=declare_parameter<int64_t>("maximum_segment_bytes",1073741824LL);maximum_segment_bytes_=mb>0?static_cast<std::uint64_t>(mb):0;auto ci=declare_parameter<int64_t>("checkpoint_interval_frames",30);checkpoint_interval_frames_=ci>0?static_cast<std::uint64_t>(ci):0;
  config_.width=positive_size("width",declare_parameter<int64_t>("width",4096));config_.height=positive_size("height",declare_parameter<int64_t>("height",3000));config_.row_stride_bytes=positive_size("row_stride_bytes",declare_parameter<int64_t>("row_stride_bytes",4096));config_.payload_bytes=positive_size("payload_bytes",declare_parameter<int64_t>("payload_bytes",12288000));config_.pixel_format=declare_parameter<std::string>("pixel_format","BayerRG8");config_.trigger_source=declare_parameter<std::string>("trigger_source","Line0");config_.trigger_activation=declare_parameter<std::string>("trigger_activation","RisingEdge");config_.exposure_auto=declare_parameter<std::string>("exposure_auto","Continuous");config_.gain_auto=declare_parameter<std::string>("gain_auto","Continuous");config_.balance_white_auto=declare_parameter<std::string>("balance_white_auto","Once");config_.balance_white_auto_profile=declare_parameter<std::string>("balance_white_auto_profile","Outdoor");config_.auto_exposure_control_priority=declare_parameter<std::string>("auto_exposure_control_priority","Gain");config_.auto_exposure_time_upper_limit_us=declare_parameter<double>("auto_exposure_time_upper_limit_us",5000.0);config_.auto_exposure_gain_upper_limit_db=declare_parameter<double>("auto_exposure_gain_upper_limit_db",12.0);config_.chunk_data_enabled=declare_parameter<bool>("chunk_data_enabled",true);trigger_channel_=declare_parameter<std::string>("trigger_channel","snapshot_rgb");trigger_topic_=declare_parameter<std::string>("trigger_topic","trigger");auto ac=declare_parameter<int64_t>("association_capacity",256);association_capacity_=ac>0?static_cast<std::size_t>(ac):0;auto aw=declare_parameter<int64_t>("association_max_wait_ms",500);association_wait_ns_=aw>0?static_cast<std::uint64_t>(aw)*1000000ULL:0;
  auto tt=declare_parameter<int64_t>("consecutive_timeout_threshold",5);auto ma=declare_parameter<int64_t>("recovery_maximum_attempts",20);auto ib=declare_parameter<int64_t>("recovery_initial_backoff_ms",250);auto xb=declare_parameter<int64_t>("recovery_maximum_backoff_ms",5000);if(tt<=0||ma<=0||ib<=0||xb<ib)throw std::invalid_argument("invalid recovery parameters");recovery_=std::make_unique<RecoverySupervisor>(RecoveryPolicy{static_cast<std::size_t>(tt),static_cast<std::size_t>(ma),std::chrono::milliseconds(ib),std::chrono::milliseconds(xb)});
  publisher_=create_publisher<ppbng_interfaces::msg::FrameMetadata>("~/frame_metadata",rclcpp::QoS(32).reliable());health_publisher_=create_publisher<ppbng_interfaces::msg::DeviceStatus>("~/device_status",rclcpp::QoS(8).reliable());fault_publisher_=create_publisher<ppbng_interfaces::msg::FaultEvent>("~/fault_event",rclcpp::QoS(8).reliable());trigger_subscription_=create_subscription<ppbng_interfaces::msg::TriggerEvent>(trigger_topic_,rclcpp::QoS(256).reliable(),[this](const ppbng_interfaces::msg::TriggerEvent&m){on_trigger(m);});prepare_service_=create_service<ppbng_interfaces::srv::PrepareDevice>("~/prepare",[this](const std::shared_ptr<ppbng_interfaces::srv::PrepareDevice::Request> q,std::shared_ptr<ppbng_interfaces::srv::PrepareDevice::Response> r){prepare(q,r);});using Request=std_srvs::srv::Trigger::Request;using Response=std_srvs::srv::Trigger::Response;start_service_=create_service<std_srvs::srv::Trigger>("~/start",[this](const std::shared_ptr<Request>,std::shared_ptr<Response> r){start(r);});stop_service_=create_service<std_srvs::srv::Trigger>("~/stop",[this](const std::shared_ptr<Request>,std::shared_ptr<Response> r){stop(r);});status_service_=create_service<std_srvs::srv::Trigger>("~/status",[this](const std::shared_ptr<Request>,std::shared_ptr<Response> r){status(r);});RCLCPP_INFO(get_logger(),"inert: ~/prepare must bind an existing session before explicit ~/start");
  arm_service_=create_service<std_srvs::srv::Trigger>("~/arm",[this](const std::shared_ptr<std_srvs::srv::Trigger::Request>,std::shared_ptr<std_srvs::srv::Trigger::Response> r){arm(r);});
 }
 ~RgbCameraNode()override{shutdown();}
private:
 static std::size_t positive_size(const char*n,int64_t v){if(v<=0)throw std::invalid_argument(std::string(n)+" must be positive");return static_cast<std::size_t>(v);}
 static std::uint64_t monotonic_ns(){return static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now().time_since_epoch()).count());}
 std::atomic<std::uint64_t> samples_incomplete_{0U},samples_dropped_{0U};
 bool safe_stream_name()const{return !stream_name_.empty()&&stream_name_.find_first_not_of("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-")==std::string::npos;}
 std::filesystem::path relative_segment()const{std::ostringstream s;s<<"segments/"<<stream_name_<<'_'<<std::setw(6)<<std::setfill('0')<<segment_index_<<".ppbseg";return s.str();}
 bool open_segment(std::string&d){auto r=ppbng_storage::SegmentWriter::create(session_root_,relative_segment());if(!r.first.ok()){d=r.first.detail;return false;}writer_=std::move(r.second);return true;}
 bool open_sidecar(std::string&d){auto p=std::filesystem::path(session_root_)/"segments"/(stream_name_+"_association.ndjson");sidecar_.clear();sidecar_.open(p,std::ios::out|std::ios::app);if(!sidecar_){d="cannot open append-only association sidecar";return false;}return true;}
 bool sidecar_record_locked(const char*state,const AssociationFrame&f,const std::optional<AssociationTrigger>&t,const std::string&detail){const auto&m=pending_metadata_.at(f.sample_id);sidecar_<<"{\"state\":\""<<state<<"\",\"segment\":"<<f.segment_id<<",\"sample\":"<<f.sample_id<<",\"sdk_frame\":"<<f.frame_id<<",\"camera_timestamp_ns\":"<<m.camera_timestamp_ns<<",\"frame_host_monotonic_ns\":"<<f.seen_ns<<",\"chunk_data_valid\":"<<(m.chunk_data_valid?"true":"false")<<",\"chunk_frame_id_valid\":"<<(m.chunk_frame_id_valid?"true":"false")<<",\"chunk_frame_id\":"<<m.chunk_frame_id<<",\"chunk_timestamp_valid\":"<<(m.chunk_timestamp_valid?"true":"false")<<",\"chunk_timestamp\":"<<m.chunk_timestamp<<",\"exposure_time_valid\":"<<(m.exposure_time_valid?"true":"false")<<",\"exposure_time_us\":"<<m.exposure_time_us<<",\"gain_valid\":"<<(m.gain_valid?"true":"false")<<",\"gain_db\":"<<m.gain_db<<",\"black_level_valid\":"<<(m.black_level_valid?"true":"false")<<",\"black_level\":"<<m.black_level<<",\"white_balance_red_valid\":"<<(m.white_balance_red_valid?"true":"false")<<",\"white_balance_red\":"<<m.white_balance_red<<",\"white_balance_blue_valid\":"<<(m.white_balance_blue_valid?"true":"false")<<",\"white_balance_blue\":"<<m.white_balance_blue<<",\"exposure_auto\":\""<<ppbng_storage::json_escape(m.exposure_auto)<<"\",\"gain_auto\":\""<<ppbng_storage::json_escape(m.gain_auto)<<"\",\"balance_white_auto\":\""<<ppbng_storage::json_escape(m.balance_white_auto)<<"\",\"trigger_valid\":"<<(t?"true":"false");if(t)sidecar_<<",\"trigger_sequence\":"<<t->sequence<<",\"pps_sequence\":"<<t->pps_sequence<<",\"controller_tick\":"<<t->offset_ticks<<",\"ticks_per_second\":"<<t->ticks_per_second<<",\"utc_ns\":"<<t->utc_ns<<",\"time_status\":"<<static_cast<unsigned>(t->time_status)<<",\"uncertainty_ns\":"<<t->uncertainty_ns<<",\"trigger_receipt_monotonic_ns\":"<<t->seen_ns;sidecar_<<",\"detail\":\""<<ppbng_storage::json_escape(detail)<<"\"}\n";sidecar_.flush();return static_cast<bool>(sidecar_);}
 bool sidecar_event_locked(const char*state,std::uint64_t segment,const std::string&detail){sidecar_<<"{\"state\":\""<<state<<"\",\"segment\":"<<segment<<",\"detail\":\""<<ppbng_storage::json_escape(detail)<<"\"}\n";sidecar_.flush();return static_cast<bool>(sidecar_);}
 struct PrepareRecord{std::string session_id,directory,message;bool accepted{false};};
 void prepare(const std::shared_ptr<ppbng_interfaces::srv::PrepareDevice::Request>&q,const std::shared_ptr<ppbng_interfaces::srv::PrepareDevice::Response>&r){std::lock_guard<std::mutex>l(mutex_);if(q->request_id.empty()){r->message="request_id required";return;}auto old=prepare_history_.find(q->request_id);if(old!=prepare_history_.end()){bool same=old->second.session_id==q->session_id&&old->second.directory==q->session_directory;r->accepted=same&&old->second.accepted;r->duplicate_request=same;r->message=same?old->second.message:"request_id payload mismatch";return;}auto finish=[&](bool ok,const std::string&m){r->accepted=ok;r->message=m;prepare_history_.emplace(q->request_id,PrepareRecord{q->session_id,q->session_directory,m,ok});};if(running_||worker_.joinable()){finish(false,"prepare refused while worker active/awaiting join");return;}if(q->session_id.empty()||q->session_directory.empty()||allowed_output_root_.empty()){finish(false,"session fields and allowed_output_root required");return;}std::error_code e;auto allowed=std::filesystem::weakly_canonical(std::filesystem::absolute(allowed_output_root_,e),e);if(e||!std::filesystem::is_directory(allowed,e)){finish(false,"allowed_output_root invalid");return;}auto root=std::filesystem::weakly_canonical(std::filesystem::absolute(q->session_directory,e),e);auto rel=root.lexically_relative(allowed);if(e||root==allowed||rel.empty()||rel.is_absolute()||*rel.begin()==".."||!std::filesystem::is_directory(root,e)||!std::filesystem::is_directory(root/"segments",e)){finish(false,"session must be existing child of allowed_output_root with segments/");return;}session_id_=q->session_id;session_root_=root.string();prepared_=true;finish(true,"existing session bound");}
 void arm(const std::shared_ptr<std_srvs::srv::Trigger::Response>&r){std::lock_guard<std::mutex>l(mutex_);if(running_||worker_.joinable()){r->message="arm requires inert joined worker";return;}
#if !PPBNG_RGB_HAS_SPINNAKER_BACKEND
  armed_=false;r->message="SDK_NOT_BUILT: rebuild ppbng_rgb with PPBNG_RGB_ENABLE_SPINNAKER=ON";return;
#endif
 auto s=validate_inert_arm_preflight(allow_hardware_,prepared_,device_id_,trigger_channel_,config_,association_capacity_,association_wait_ns_);if(!s.ok()||session_root_.empty()||!safe_stream_name()||timeout_ms_<=0||checkpoint_interval_frames_==0||maximum_segment_bytes_<=config_.payload_bytes+ppbng_storage::SegmentRolloverPolicy::record_overhead_bytes()){armed_=false;r->message=s.ok()?"storage/runtime parameters invalid":s.detail;return;}armed_=true;armed_binding_=session_id_+"\n"+session_root_;r->success=true;r->message="inert preflight armed; no file created and no SDK/System/device access performed";}
 void release_failed()noexcept{writer_.reset();sidecar_.close();associator_.reset();pending_metadata_.clear();backend_->stop(std::chrono::milliseconds(timeout_ms_>0?timeout_ms_:1000));stop_source_.reset();running_=false;armed_=false;}
 void fail_start(const std::shared_ptr<std_srvs::srv::Trigger::Response>&r,const std::string&d){faulted_=true;fault_detail_=d;r->success=false;r->message=d;}
 void start(const std::shared_ptr<std_srvs::srv::Trigger::Response>&r){
  std::lock_guard<std::mutex>l(mutex_);if(worker_.joinable()){r->message="previous worker must be joined with ~/stop before restart";return;}if(running_){r->message="already running";return;}faulted_=false;fault_detail_.clear();if(!armed_||armed_binding_!=session_id_+"\n"+session_root_){r->message="successful inert ~/arm for this prepared session is required";return;}if(!allow_hardware_){r->message="allow_hardware_access is false";return;}
  if(!prepared_||device_id_.empty()||session_id_.empty()||session_root_.empty()||!safe_stream_name()||trigger_channel_.empty()||trigger_topic_.empty()||association_capacity_==0||association_wait_ns_==0||timeout_ms_<=0||checkpoint_interval_frames_==0||maximum_segment_bytes_<=config_.payload_bytes+ppbng_storage::SegmentRolloverPolicy::record_overhead_bytes()){r->message="successful ~/prepare, identity, trigger channel/topic, association bounds and usable storage configuration are required";return;}
  StartCleanupGuard cleanup([this](){release_failed();});StopSource probe;std::vector<std::string>ids;auto checked=[&](Status s){if(!s.ok()){fail_start(r,s.detail);return false;}return true;};if(!checked(backend_->discover(std::chrono::milliseconds(timeout_ms_),probe.token(),ids)))return;std::string selected;if(!checked(select_unique_device_id(device_id_,ids,selected)))return;if(!checked(backend_->open(selected,std::chrono::milliseconds(timeout_ms_),probe.token())))return;if(!checked(backend_->configure(config_,std::chrono::milliseconds(timeout_ms_),probe.token())))return;if(!checked(backend_->readback(std::chrono::milliseconds(timeout_ms_),probe.token(),readback_)))return;if(!checked(validate_raw_bayer_contract(readback_)))return;
  segment_index_=0;sample_sequence_=0;reconnect_events_=0;samples_incomplete_=0;samples_dropped_=0;recovery_->recovered();std::string detail;if(!open_segment(detail)){fail_start(r,"segment create failed: "+detail);return;}if(!open_sidecar(detail)){fail_start(r,"association sidecar open failed: "+detail);return;}associator_=std::make_unique<SequenceAssociator>(association_capacity_,association_wait_ns_,get_parameter("association_evidence_confirmed").as_bool());{std::lock_guard<std::mutex>a(association_mutex_);auto x=associator_->reset(0);(void)x;if(!sidecar_event_locked("SEGMENT_RESET",0,"capture start; anchors cleared")){fail_start(r,"association sidecar initial write failed");return;}}if(!checked(backend_->arm(std::chrono::milliseconds(timeout_ms_),probe.token())))return;stop_source_=std::make_unique<StopSource>();running_=true;try{worker_=std::thread([this](){capture_loop();});}catch(const std::exception&e){fail_start(r,std::string("worker creation failed: ")+e.what());return;}cleanup.commit();r->success=true;r->message="RGB armed with checksummed segmented recording and append-only association audit";
 }
 void stop(const std::shared_ptr<std_srvs::srv::Trigger::Response>&r){shutdown();std::lock_guard<std::mutex>l(mutex_);r->success=!faulted_;r->message=faulted_?"stopped after fault: "+fault_detail_:"RGB acquisition stopped";publish_health_snapshot(ppbng_interfaces::msg::DeviceStatus::LIFECYCLE_DISCONNECTED,faulted_?ppbng_interfaces::msg::DeviceStatus::HEALTH_FAULT:ppbng_interfaces::msg::DeviceStatus::HEALTH_OK,r->message);}
 void status(const std::shared_ptr<std_srvs::srv::Trigger::Response>&r){std::lock_guard<std::mutex>l(mutex_);r->success=running_&&!faulted_;r->message=faulted_?"FAULT: "+fault_detail_:(running_?"RUNNING":"INERT");}
 void shutdown()noexcept{std::unique_lock<std::mutex>l(mutex_);if(stop_source_)stop_source_->request_stop();recovery_cv_.notify_all();l.unlock();if(worker_.joinable())worker_.join();l.lock();backend_->stop(std::chrono::milliseconds(timeout_ms_>0?timeout_ms_:1000));writer_.reset();running_=false;recovering_=false;armed_=false;stop_source_.reset();}
 void publish_health_snapshot(std::uint8_t lifecycle,std::uint8_t health,const std::string&d){ppbng_interfaces::msg::DeviceStatus s;s.status_host_monotonic_ns=monotonic_ns();s.session_id=session_id_;s.device_id=device_id_;s.required=true;s.lifecycle_state=lifecycle;s.health=health;s.segment_id=static_cast<uint32_t>(std::min<std::uint64_t>(segment_index_,(std::numeric_limits<uint32_t>::max)()));s.last_sample_valid=sample_sequence_>0;s.last_sample_sequence=sample_sequence_;s.samples_received=sample_sequence_;s.samples_incomplete=samples_incomplete_;s.samples_dropped=samples_dropped_;s.reconnect_attempts=static_cast<uint32_t>(std::min<std::uint64_t>(reconnect_events_,(std::numeric_limits<uint32_t>::max)()));if(validate_raw_bayer_contract(readback_).ok()){s.active_config_hash=std::to_string(configuration_hash(readback_));s.actual_setting_keys={"width","height","row_stride_bytes","payload_bytes","pixel_format","trigger_source","trigger_activation","hardware_trigger","control_access"};s.actual_setting_values={std::to_string(readback_.width),std::to_string(readback_.height),std::to_string(readback_.row_stride_bytes),std::to_string(readback_.payload_bytes),readback_.pixel_format,readback_.trigger_source,readback_.trigger_activation,readback_.hardware_trigger?"true":"false",readback_.control_access?"true":"false"};}s.detail=d;health_publisher_->publish(s);}
 void publish_recovery(const std::string&code,const std::string&d,bool recovered=false){publish_health_snapshot(recovered?ppbng_interfaces::msg::DeviceStatus::LIFECYCLE_STREAMING:ppbng_interfaces::msg::DeviceStatus::LIFECYCLE_RECOVERING,recovered?ppbng_interfaces::msg::DeviceStatus::HEALTH_OK:ppbng_interfaces::msg::DeviceStatus::HEALTH_DEGRADED,d);ppbng_interfaces::msg::FaultEvent e;e.event_id=device_id_+"-"+code+"-"+std::to_string(++fault_event_sequence_);e.session_id=session_id_;e.source_id=device_id_;e.fault_code=code;e.severity=recovered?e.SEVERITY_INFO:e.SEVERITY_WARNING;e.first_host_monotonic_ns=monotonic_ns();e.last_host_monotonic_ns=e.first_host_monotonic_ns;e.occurrence_count=1;e.latched=false;e.causes_global_stop=false;e.detail=d;fault_publisher_->publish(e);}
 void worker_fault(const std::string&d,const std::string&code="CAMERA_WORKER_FAULT",bool global=false){std::lock_guard<std::mutex>l(mutex_);faulted_=true;fault_detail_=d;if(stop_source_)stop_source_->request_stop();recovery_cv_.notify_all();RCLCPP_ERROR(get_logger(),"RGB fault: %s",d.c_str());ppbng_interfaces::msg::DeviceStatus s;s.session_id=session_id_;s.device_id=device_id_;s.required=true;s.lifecycle_state=s.LIFECYCLE_STOPPING;s.health=s.HEALTH_FAULT;s.segment_id=static_cast<uint32_t>(segment_index_);s.last_sample_valid=sample_sequence_>0;s.last_sample_sequence=sample_sequence_;s.samples_received=sample_sequence_;s.reconnect_attempts=static_cast<uint32_t>(std::min<std::uint64_t>(reconnect_events_,(std::numeric_limits<uint32_t>::max)()));s.detail=d;health_publisher_->publish(s);ppbng_interfaces::msg::FaultEvent e;e.event_id=device_id_+"-"+code+"-"+std::to_string(++fault_event_sequence_);e.session_id=session_id_;e.source_id=device_id_;e.fault_code=code;e.severity=global?e.SEVERITY_FATAL:e.SEVERITY_ERROR;e.first_host_monotonic_ns=monotonic_ns();e.last_host_monotonic_ns=e.first_host_monotonic_ns;e.occurrence_count=1;e.latched=true;e.causes_global_stop=global;e.detail=d;fault_publisher_->publish(e);}
 bool recover_acquisition(const std::string&reason,const StopToken&token){
  recovering_=true;recovery_->begin_episode();publish_recovery("CAMERA_RECOVERY_STARTED",reason);backend_->stop(std::chrono::milliseconds(timeout_ms_));std::string detail;
  if(sidecar_.is_open()&&!reset_association(segment_index_,detail)){worker_fault(detail,"ASSOCIATION_SIDECAR_WRITE_FAILED",true);recovering_=false;return false;}
  if(writer_){auto cp=writer_->checkpoint();if(!cp.first.ok()){worker_fault("recovery checkpoint failed: "+cp.first.detail,"CAMERA_STORAGE_FAULT",true);writer_.reset();recovering_=false;return false;}writer_.reset();}
  if(sidecar_.is_open()){sidecar_.flush();if(!sidecar_){worker_fault("association sidecar flush failed during recovery","ASSOCIATION_SIDECAR_WRITE_FAILED",true);sidecar_.close();recovering_=false;return false;}sidecar_.close();}
  while(!token.stop_requested()){auto attempt=recovery_->next_attempt();if(!attempt.allowed){worker_fault("bounded RGB recovery exhausted after "+std::to_string(attempt.number)+" attempts","CAMERA_RECOVERY_EXHAUSTED",false);recovering_=false;return false;}++reconnect_events_;publish_recovery("CAMERA_RECOVERY_RETRY","attempt "+std::to_string(attempt.number)+" after "+std::to_string(attempt.backoff.count())+" ms");
   {std::unique_lock<std::mutex>l(recovery_mutex_);if(recovery_cv_.wait_for(l,attempt.backoff,[&](){return token.stop_requested();})){recovering_=false;return false;}}
   std::vector<std::string>ids;std::string selected;Status s=backend_->discover(std::chrono::milliseconds(timeout_ms_),token,ids);if(s.ok())s=select_unique_device_id(device_id_,ids,selected);if(s.ok())s=backend_->open(selected,std::chrono::milliseconds(timeout_ms_),token);if(s.ok())s=backend_->configure(config_,std::chrono::milliseconds(timeout_ms_),token);if(s.ok())s=backend_->readback(std::chrono::milliseconds(timeout_ms_),token,readback_);if(s.ok())s=validate_raw_bayer_contract(readback_);if(s.ok())s=backend_->arm(std::chrono::milliseconds(timeout_ms_),token);
   if(!s.ok()){backend_->stop(std::chrono::milliseconds(timeout_ms_));if(s.code==ErrorCode::cancelled&&token.stop_requested()){recovering_=false;return false;}publish_recovery("CAMERA_RECOVERY_ATTEMPT_FAILED","attempt "+std::to_string(attempt.number)+": "+s.detail);continue;}
   ++segment_index_;if(!open_segment(detail)){backend_->stop(std::chrono::milliseconds(timeout_ms_));worker_fault("recovery segment create failed: "+detail,"CAMERA_STORAGE_FAULT",true);recovering_=false;return false;}if(!open_sidecar(detail)){backend_->stop(std::chrono::milliseconds(timeout_ms_));writer_.reset();worker_fault("recovery sidecar open failed: "+detail,"ASSOCIATION_SIDECAR_WRITE_FAILED",true);recovering_=false;return false;}if(!reset_association(segment_index_,detail)){backend_->stop(std::chrono::milliseconds(timeout_ms_));writer_.reset();sidecar_.close();worker_fault(detail,"ASSOCIATION_SIDECAR_WRITE_FAILED",true);recovering_=false;return false;}
   recovery_->recovered();recovering_=false;publish_recovery("CAMERA_RECOVERED","strict identity/configuration/readback/arm succeeded; recording resumed in new segment",true);return true;}
  recovering_=false;return false;
 }
 bool process_association_locked(AssociationResult&&x,std::string&failure){if(x.degraded&&!sidecar_event_locked("DEGRADED",segment_index_,x.detail)){failure="association sidecar degraded-event write failed";return false;}for(const auto&s:x.settlements){auto state=s.kind==SettlementKind::matched?"MATCHED":(s.kind==SettlementKind::consistent_unverified?"CONSISTENT_UNVERIFIED":"UNMATCHED");if(!sidecar_record_locked(state,s.frame,s.trigger,s.detail)){failure="association sidecar settlement write failed";return false;}if(s.kind!=SettlementKind::matched)++samples_incomplete_;auto p=pending_metadata_.find(s.frame.sample_id);if(p!=pending_metadata_.end()){publish(p->second,s.frame.segment_id,s.frame.sample_id,s.trigger,state,s.kind==SettlementKind::matched);pending_metadata_.erase(p);}}return true;}
 bool reset_association(std::uint64_t segment,std::string&failure){std::lock_guard<std::mutex>a(association_mutex_);if(!associator_)return true;auto x=associator_->reset(segment);if(!process_association_locked(std::move(x),failure))return false;return sidecar_event_locked("SEGMENT_RESET",segment,"segment boundary; anchors cleared")||(failure="association sidecar reset write failed",false);}
 void on_trigger(const ppbng_interfaces::msg::TriggerEvent&m){if(!running_||recovering_||m.channel!=trigger_channel_)return;AssociationTrigger t;t.sequence=m.channel_sequence;t.pps_sequence=m.pps_sequence;t.offset_ticks=m.offset_ticks;t.ticks_per_second=m.ticks_per_second;t.uncertainty_ns=m.time_quality.uncertainty_ns;t.seen_ns=monotonic_ns();t.time_status=m.time_quality.status;t.utc_ns=static_cast<std::int64_t>(m.time_quality.utc_time.sec)*1000000000LL+static_cast<std::int64_t>(m.time_quality.utc_time.nanosec);std::string failure;{std::lock_guard<std::mutex>a(association_mutex_);if(!associator_||!running_||recovering_)return;if(t.ticks_per_second==0){sidecar_event_locked("DEGRADED",segment_index_,"trigger rejected: ticks_per_second is zero");failure="invalid trigger timing";}else{auto x=associator_->trigger(t);if(!x.accepted)failure=x.detail;if(!process_association_locked(std::move(x),failure)&&failure.empty())failure="association processing failed";auto expired=associator_->expire(t.seen_ns);if(!process_association_locked(std::move(expired),failure)&&failure.empty())failure="association expiry failed";}}if(!failure.empty())worker_fault(failure,failure.find("sidecar")!=std::string::npos?"ASSOCIATION_SIDECAR_WRITE_FAILED":"TRIGGER_ASSOCIATION_FAULT",failure.find("sidecar")!=std::string::npos);}
 bool append(const FrameLease&f,std::uint64_t sample,std::string&d){ppbng_storage::SegmentRolloverPolicy p(maximum_segment_bytes_);if(p.should_rollover(writer_->committed_bytes(),f.size())){auto cp=writer_->checkpoint();if(!cp.first.ok()){d=cp.first.detail;return false;}writer_.reset();++segment_index_;if(!open_segment(d))return false;if(!reset_association(segment_index_,d))return false;}ppbng_storage::FrameEnvelope e;e.sample_id=sample;auto s=writer_->append(e,reinterpret_cast<const std::byte*>(f.data()),f.size());if(!s.ok()){d=s.detail;return false;}sample_sequence_=sample;if(sample%checkpoint_interval_frames_==0){auto cp=writer_->checkpoint();if(!cp.first.ok()){d=cp.first.detail;return false;}}return true;}
 void capture_loop()noexcept{try{const auto token=stop_source_->token();while(!token.stop_requested()){auto result=backend_->next_frame(std::chrono::milliseconds(timeout_ms_),token);if(result.status.code==ErrorCode::timeout){std::string failure;{std::lock_guard<std::mutex>a(association_mutex_);if(associator_)process_association_locked(associator_->expire(monotonic_ns()),failure);}if(!failure.empty()){worker_fault(failure,"ASSOCIATION_SIDECAR_WRITE_FAILED",true);break;}if(recovery_->observe_timeout()&&!recover_acquisition("consecutive acquisition timeouts reached configured threshold",token))break;continue;}if(!result.frame){if(result.status.code==ErrorCode::cancelled&&token.stop_requested())break;if(!recover_acquisition("acquisition/transport fault: "+result.status.detail,token))break;continue;}recovery_->observe_frame();auto d=describe_runtime_frame(result.frame.info(),readback_);if(d.validation_detail!="raw Bayer payload validated"){result.frame.release();if(!recover_acquisition("invalid/incomplete runtime frame: "+d.validation_detail,token))break;continue;}const auto sample=sample_sequence_+1U;std::string detail;if(!append(result.frame,sample,detail)){worker_fault("segment append failed: "+detail,detail.find("sidecar")!=std::string::npos?"ASSOCIATION_SIDECAR_WRITE_FAILED":"CAMERA_STORAGE_FAULT",true);break;}{std::lock_guard<std::mutex>a(association_mutex_);AssociationFrame f{d.sdk_frame_counter,sample,segment_index_,d.host_receive_monotonic_ns};pending_metadata_[sample]=d;if(!sidecar_record_locked("PENDING",f,{},"raw payload committed; awaiting exact sequence-delta match")){detail="association sidecar pending write failed";}else{auto x=associator_->frame(f);if(!x.accepted&&x.settlements.empty())x.settlements.push_back({SettlementKind::unmatched,f,{},x.detail});process_association_locked(std::move(x),detail);if(detail.empty())process_association_locked(associator_->expire(monotonic_ns()),detail);}}if(!detail.empty()){worker_fault(detail,detail.find("sidecar")!=std::string::npos?"ASSOCIATION_SIDECAR_WRITE_FAILED":"FRAME_ASSOCIATION_FAULT",detail.find("sidecar")!=std::string::npos);break;}}}catch(const std::exception&e){worker_fault(std::string("unhandled exception: ")+e.what());}catch(...){worker_fault("unhandled non-standard exception");}backend_->stop(std::chrono::milliseconds(timeout_ms_));std::string association_failure;if(sidecar_.is_open())reset_association(segment_index_,association_failure);if(!association_failure.empty())worker_fault(association_failure,"ASSOCIATION_SIDECAR_WRITE_FAILED",true);if(writer_){auto cp=writer_->checkpoint();if(!cp.first.ok())worker_fault("final checkpoint failed: "+cp.first.detail,"CAMERA_STORAGE_FAULT",true);writer_.reset();}if(sidecar_.is_open()){sidecar_.flush();if(!sidecar_)worker_fault("final sidecar flush failed","ASSOCIATION_SIDECAR_WRITE_FAILED",true);sidecar_.close();}recovering_=false;running_=false;}
 void publish(const RuntimeFrameDescriptor&d,std::uint64_t segment,std::uint64_t sample,const std::optional<AssociationTrigger>&t,const char*association,bool matched){ppbng_interfaces::msg::FrameMetadata m;m.stamp.session_id=session_id_;m.stamp.device_id=device_id_;m.stamp.segment_id=static_cast<uint32_t>(std::min<std::uint64_t>(segment,(std::numeric_limits<uint32_t>::max)()));m.stamp.sample_sequence=sample;m.stamp.trigger_channel=trigger_channel_;if(t){m.stamp.trigger_sequence=t->sequence;m.stamp.pps_sequence=t->pps_sequence;m.stamp.controller_tick=t->offset_ticks;m.stamp.controller_ticks_per_second=t->ticks_per_second;m.stamp.time_quality.pps_sequence=t->pps_sequence;m.stamp.time_quality.hardware_tick=t->offset_ticks;m.stamp.time_quality.uncertainty_ns=t->uncertainty_ns;}m.stamp.time_quality.status=matched&&t?t->time_status:m.stamp.time_quality.UNSYNCED;if(matched&&t&&t->utc_ns>0){m.stamp.time_quality.utc_time.sec=static_cast<int32_t>(t->utc_ns/1000000000LL);m.stamp.time_quality.utc_time.nanosec=static_cast<uint32_t>(t->utc_ns%1000000000LL);}m.stamp.time_quality.detail=std::string(association)+(matched?" by segment-local SDK-frame/channel-sequence delta":"; canonical UTC withheld; raw evidence is retained in association sidecar");m.stamp.camera_frame_id_valid=true;m.stamp.camera_frame_id=d.sdk_frame_counter;m.stamp.camera_timestamp_valid=true;m.stamp.camera_timestamp=d.camera_timestamp_ns;m.stamp.host_receive_monotonic_ns=d.host_receive_monotonic_ns;m.transport_width=d.transport_width;m.transport_height=d.transport_height;m.row_stride_bytes=d.row_stride_bytes;m.payload_size_bytes=d.payload_size_bytes;m.pixel_format=d.pixel_format;m.byte_order=m.BYTE_ORDER_UNKNOWN;m.image_width=d.transport_width;m.image_height=d.transport_height;m.image_data_length_bytes=d.payload_size_bytes;m.geometry_source=m.GEOMETRY_SOURCE_CAMERA_READBACK;m.raw_payload_preserved=d.raw_payload_preserved;m.complete=d.complete;m.validation_detail=d.validation_detail+"; association="+association;m.chunk_data_valid=d.chunk_data_valid;m.chunk_frame_id_valid=d.chunk_frame_id_valid;m.chunk_frame_id=d.chunk_frame_id;m.chunk_timestamp_valid=d.chunk_timestamp_valid;m.chunk_timestamp=d.chunk_timestamp;m.exposure_time_valid=d.exposure_time_valid;m.exposure_time_us=d.exposure_time_us;m.gain_valid=d.gain_valid;m.gain_db=d.gain_db;m.black_level_valid=d.black_level_valid;m.black_level=d.black_level;m.white_balance_red_valid=d.white_balance_red_valid;m.white_balance_red=d.white_balance_red;m.white_balance_blue_valid=d.white_balance_blue_valid;m.white_balance_blue=d.white_balance_blue;m.exposure_auto=d.exposure_auto;m.gain_auto=d.gain_auto;m.balance_white_auto=d.balance_white_auto;m.settings_source="SPINNAKER_CHUNK_PLUS_POST_FRAME_WHITE_BALANCE_READBACK";publisher_->publish(m);}
 std::mutex mutex_,association_mutex_,recovery_mutex_;std::condition_variable recovery_cv_;std::atomic_bool running_{false},recovering_{false};bool faulted_{false},allow_hardware_{},prepared_{false},armed_{false};int timeout_ms_{};std::size_t association_capacity_{};std::uint64_t association_wait_ns_{},maximum_segment_bytes_{},checkpoint_interval_frames_{};std::atomic<std::uint64_t> segment_index_{0U},sample_sequence_{0U},reconnect_events_{0U},fault_event_sequence_{0U};std::string fault_detail_,device_id_,session_id_,session_root_,stream_name_,allowed_output_root_,trigger_channel_,trigger_topic_,armed_binding_;std::unordered_map<std::string,PrepareRecord>prepare_history_;std::unordered_map<std::uint64_t,RuntimeFrameDescriptor>pending_metadata_;RgbConfiguration config_;RgbReadback readback_;std::unique_ptr<SpinnakerRgbBackend>backend_;std::unique_ptr<StopSource>stop_source_;std::unique_ptr<ppbng_storage::SegmentWriter>writer_;std::unique_ptr<SequenceAssociator>associator_;std::unique_ptr<RecoverySupervisor>recovery_;std::ofstream sidecar_;std::thread worker_;rclcpp::Publisher<ppbng_interfaces::msg::FrameMetadata>::SharedPtr publisher_;rclcpp::Publisher<ppbng_interfaces::msg::DeviceStatus>::SharedPtr health_publisher_;rclcpp::Publisher<ppbng_interfaces::msg::FaultEvent>::SharedPtr fault_publisher_;rclcpp::Subscription<ppbng_interfaces::msg::TriggerEvent>::SharedPtr trigger_subscription_;rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr arm_service_,start_service_,stop_service_,status_service_;rclcpp::Service<ppbng_interfaces::srv::PrepareDevice>::SharedPtr prepare_service_;
};}
int main(int argc,char**argv){rclcpp::init(argc,argv);rclcpp::spin(std::make_shared<ppbng_rgb::RgbCameraNode>());rclcpp::shutdown();return 0;}
