#include "ppbng_thermal/sequence_association.hpp"
#include <limits>
#include <stdexcept>
namespace ppbng_thermal {
SequenceAssociator::SequenceAssociator(std::size_t c,std::uint64_t w,bool confirmed):capacity_(c),wait_ns_(w),evidence_confirmed_(confirmed){if(!c||!w)throw std::invalid_argument("positive association capacity/wait required");}
void SequenceAssociator::append(AssociationResult&a,AssociationResult&&b){a.accepted=a.accepted&&b.accepted;a.degraded=a.degraded||b.degraded;if(!b.detail.empty())a.detail=b.detail;a.settlements.insert(a.settlements.end(),std::make_move_iterator(b.settlements.begin()),std::make_move_iterator(b.settlements.end()));}
AssociationResult SequenceAssociator::reset(std::uint64_t s){AssociationResult r;for(auto&v:frames_)r.settlements.push_back({SettlementKind::unmatched,v.second,{},"segment reset before match"});r.degraded=!frames_.empty()||!triggers_.empty();r.detail=r.degraded?"segment reset discarded pending association":"segment reset";frames_.clear();triggers_.clear();frame_anchor_.reset();trigger_anchor_.reset();last_frame_.reset();last_trigger_.reset();segment_=s;return r;}
AssociationResult SequenceAssociator::frame(AssociationFrame f){AssociationResult r;if(f.segment_id!=segment_){r.accepted=false;r.degraded=true;r.detail="frame segment mismatch";return r;}if(last_frame_&&f.frame_id<=*last_frame_){r.accepted=false;r.degraded=true;r.detail="frame counter duplicate/regression";return r;}if(last_frame_&&f.frame_id-*last_frame_>1){r.degraded=true;r.detail="frame counter gap";}if(frames_.size()>=capacity_){r.accepted=false;r.degraded=true;r.detail="frame pending overflow";r.settlements.push_back({SettlementKind::unmatched,f,{},r.detail});return r;}if(!frame_anchor_)frame_anchor_=f.frame_id;last_frame_=f.frame_id;frames_.emplace(f.frame_id,f);append(r,drain());return r;}
AssociationResult SequenceAssociator::trigger(AssociationTrigger t){AssociationResult r;if(last_trigger_&&t.sequence<=*last_trigger_){r.accepted=false;r.degraded=true;r.detail="trigger counter duplicate/regression";return r;}if(last_trigger_&&t.sequence-*last_trigger_>1){r.degraded=true;r.detail="trigger counter gap";}if(triggers_.size()>=capacity_){r.accepted=false;r.degraded=true;r.detail="trigger pending overflow";return r;}if(!trigger_anchor_)trigger_anchor_=t.sequence;last_trigger_=t.sequence;triggers_.emplace(t.sequence,t);append(r,drain());return r;}
AssociationResult SequenceAssociator::drain(){AssociationResult r;if(!frame_anchor_||!trigger_anchor_)return r;for(auto i=frames_.begin();i!=frames_.end();){auto d=i->first-*frame_anchor_;if(d>(std::numeric_limits<std::uint64_t>::max)()-*trigger_anchor_){r.accepted=false;r.degraded=true;r.detail="sequence mapping overflow";break;}auto t=triggers_.find(*trigger_anchor_+d);if(t==triggers_.end()){++i;continue;}r.settlements.push_back({evidence_confirmed_?SettlementKind::matched:SettlementKind::consistent_unverified,i->second,t->second,evidence_confirmed_?"exact sequence delta with externally confirmed semantics":"constant delta only; missed-trigger/frame FIFO ambiguity is not excluded"});triggers_.erase(t);i=frames_.erase(i);}return r;}
AssociationResult SequenceAssociator::expire(std::uint64_t n){AssociationResult r;for(auto i=frames_.begin();i!=frames_.end();)if(n>=i->second.seen_ns&&n-i->second.seen_ns>=wait_ns_){r.settlements.push_back({SettlementKind::unmatched,i->second,{},"association wait expired"});i=frames_.erase(i);r.degraded=true;}else ++i;for(auto i=triggers_.begin();i!=triggers_.end();)if(n>=i->second.seen_ns&&n-i->second.seen_ns>=wait_ns_){i=triggers_.erase(i);r.degraded=true;}else ++i;if(r.degraded)r.detail="expired unmatched association observations";return r;}
}
