<?xml version="1.0"?>
<package format="3">
  <name>ppbng_orchestrator</name>
  <version>0.1.0</version>
  <description>Hardware-independent PPBNG acquisition task state machine.</description>
  <maintainer email="yl3663@cornell.edu">Yiyuan Lin</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

